#!/usr/bin/python
# -*- coding: utf-8 -*-
import fileinput
import os
def nulervoor(i):
    if i < 10:
        i = ("0" + i)
    return i

if open('/var/www/html/São_Paulo_Powered_By_Victor/data/dienstregelingBg.json', 'r').read().find("01H") < 0:
    nummer = 1
    while nummer < 24:
        with open('/var/www/html/São_Paulo_Powered_By_Victor/data/dienstregelingBg.json', 'a') as dienstregeling:
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H06M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"06", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H21M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"21", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H36M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"36", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H51M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"51", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"0", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"0", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"6", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"6", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"12", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"12", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"18", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"18", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"24", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"24", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"30", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"30", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"36", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"36", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"42", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"42", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"48", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"48", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"1", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"54", "bestemming":"Chácara Klabin", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Brooklin, Campo Belo, Eucaliptos, Moema, AACD - Servidor, Hospital São Paulo, Santa Cruz", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"2", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"54", "bestemming":"Capão Redondo", "vertrekspoor":"1","soort":"Metrô","vertraging":"","tussenstations":"Alto da Boa Vista, Adolfo Pinheiro, Largo Treze, Santo Amaro, Giovanni Gronchi, Villa das Belezas, Campo Limpo", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')

            if nummer == 24:
                dienstregeling.write(']}')
            print (nummer)
            nummer += 1
        dienstregeling.close()
else: print ('Niets gedaan')

print ('Ik ben klaar')


