#!/usr/bin/python
# -*- coding: utf-8 -*-
import fileinput
import os
def nulervoor(i):
    if i < 10:
        i = ("0" + i)
    return i

if open('/var/www/html/FR/data/dienstregelingBf.json', 'r').read().find("01H") < 0:
    nummer = 1
    while nummer < 24:
        with open('/var/www/html/FR/data/dienstregelingBf.json', 'a') as dienstregeling:
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H06M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"06", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H21M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"21", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H36M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"36", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H51M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"51", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            dienstregeling.write('  , { "treincode":"BF-TR006-R1-' + '{:02}'.format(nummer) + 'H00M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"00", "bestemming":"Mer Nouveau", "vertrekspoor":"2b","soort":"T.E. Regional","vertraging":"","tussenstations":"Vignais", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write('  , { "treincode":"BF-TR004-R2-' + '{:02}'.format(nummer) + 'H09M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"09", "bestemming":"Nouveau Paris Sud", "vertrekspoor":"1a","soort":"T.E. Regional","vertraging":"","tussenstations":"Plateau de Fleurs, Fleurmont, Champ Derrière, Plainebourg Midi, Plainebourg, Gendte Central, Formarais, Nouveau Paris Central", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write('  , { "treincode":"BF-IC001-R1-' + '{:02}'.format(nummer) + 'H12M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"12", "bestemming":"Sudport", "vertrekspoor":"4","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Gendte Central, Nouveau Paris Central, Leusden", "bericht":"Stopt ook in Plainebourg", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write('  , { "treincode":"BF-TR006-R1-' + '{:02}'.format(nummer) + 'H15M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"15", "bestemming":"Mer Nouveau", "vertrekspoor":"1b","soort":"T.E. Regional","vertraging":"","tussenstations":"Vignais", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}\n')
            dienstregeling.write('  , { "treincode":"BF-TR004-R2-' + '{:02}'.format(nummer) + 'H24M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"24", "bestemming":"Etendeau", "vertrekspoor":"2a","soort":"T.E. Regional","vertraging":"","tussenstations":"Plateau de Fleurs, Fleurmont, Champ Derrière, Plainebourg Midi, Plainebourg, Gendte Central, Formarais, Nouveau Paris Central, Nouveau Paris Sud", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write('  , { "treincode":"BF-IC001-R1-' + '{:02}'.format(nummer) + 'H27M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"27", "bestemming":"Sudport", "vertrekspoor":"3","soort":"T.E. Regional","vertraging":"","tussenstations":"Gendte Central, Nouveau Paris Central, Leusden", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write('  , { "treincode":"BF-TR006-R1-' + '{:02}'.format(nummer) + 'H00M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"30", "bestemming":"Mer Nouveau", "vertrekspoor":"2b","soort":"T.E. Regional","vertraging":"","tussenstations":"Vignais", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write('  , { "treincode":"BF-TR004-R2-' + '{:02}'.format(nummer) + 'H09M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"39", "bestemming":"Nouveau Paris Sud", "vertrekspoor":"1a","soort":"T.E. Regional","vertraging":"","tussenstations":"Plateau de Fleurs, Fleurmont, Champ Derrière, Plainebourg Midi, Plainebourg, Gendte Central, Formarais, Nouveau Paris Central", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write('  , { "treincode":"BF-IC001-R1-' + '{:02}'.format(nummer) + 'H12M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"42", "bestemming":"Sudport", "vertrekspoor":"4","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Gendte Central, Nouveau Paris Central, Leusden", "bericht":"Stopt ook in Plainebourg", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write('  , { "treincode":"BF-TR006-R1-' + '{:02}'.format(nummer) + 'H15M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"45", "bestemming":"Mer Nouveau", "vertrekspoor":"1b","soort":"T.E. Regional","vertraging":"","tussenstations":"Vignais", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}\n')
            dienstregeling.write('  , { "treincode":"BF-TR004-R2-' + '{:02}'.format(nummer) + 'H24M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"54", "bestemming":"Etendeau", "vertrekspoor":"2a","soort":"T.E. Regional","vertraging":"","tussenstations":"Plateau de Fleurs, Fleurmont, Champ Derrière, Plainebourg Midi, Plainebourg, Gendte Central, Formarais, Nouveau Paris Central, Nouveau Paris Sud", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write('  , { "treincode":"BF-IC001-R1-' + '{:02}'.format(nummer) + 'H27M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"57", "bestemming":"Sudport", "vertrekspoor":"3","soort":"T.E. Regional","vertraging":"","tussenstations":"Gendte Central, Nouveau Paris Central, Leusden", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            print (nummer)
            nummer += 1
        dienstregeling.close()
else: print ('Niets gedaan')

print ('Ik ben klaar')


