#!/usr/bin/python
# -*- coding: utf-8 -*-
import fileinput
import os
def nulervoor(i):
    if i < 10:
        i = ("0" + i)
    return i

if open('/var/www/html/FR/data/dienstregelingGc.json', 'r').read().find("01H") < 0:
    nummer = 1
    while nummer < 24:
        with open('/var/www/html/FR/data/dienstregelingGc.json', 'a') as dienstregeling:
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H06M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"06", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H21M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"21", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H36M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"36", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            #dienstregeling.write(', { "treincode":"GV-TR003-R2-' + '{:02}'.format(nummer) + 'H51M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"51", "bestemming":"Nouveau Paris Nord", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"0","tussenstations":"Gendte Central, Plainebourg, Ville de Finpont, Canauxbourg, Nouveau Paris Central, Châteauville", "bericht":"0", "storingsoorzaak":"0", "oudeBestemming":"0", "oudVertrekspoor":"0","rijdtNiet":"0"} \n')
            dienstregeling.write(', { "treincode":"GC-IC001-R1-' + '{:02}'.format(nummer) + 'H03M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"03", "bestemming":"Baie de Fleurs", "vertrekspoor":"4","soort":"Intercité","vertraging":"","tussenstations":"", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR004-R1-' + '{:02}'.format(nummer) + 'H04M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"04", "bestemming":"Baie de Fleurs", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Plainebourg Midi, Champ Derrière, Fleurmont, Plateau de Fleurs", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-IC001-R2-' + '{:02}'.format(nummer) + 'H06M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"06", "bestemming":"Sudport", "vertrekspoor":"3","soort":"Intercité","vertraging":"","tussenstations":"Nouveau Paris Central, Leusden", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR004-R2-' + '{:02}'.format(nummer) + 'H07M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"07", "bestemming":"Etendeau", "vertrekspoor":"2","soort":"T.E. Regional","vertraging":"","tussenstations":"Gendte Quatier Avant, Formarais, Nouveau Paris C., Nouveau Paris Sud", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR003-R2-' + '{:02}'.format(nummer) + 'H08M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"08", "bestemming":"Nouveau Paris Central", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Ville de Finpont, Canauxbourg, Canauxbourg Sud, Nouveau Paris Nord, Calais Midi", "bericht":"Reistip: TER Etendeau van ' + '{:02}'.format(nummer + 1) + ':08 is eerder in Nouveau Paris C.", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR003-R2-' + '{:02}'.format(nummer) + 'H13M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"13", "bestemming":"Gendte Ville Basse", "vertrekspoor":"2","soort":"T.E. Regional","vertraging":"","tussenstations":"", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-IC001-R1-' + '{:02}'.format(nummer) + 'H18M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"18", "bestemming":"Baie de Fleurs", "vertrekspoor":"4","soort":"Intercité","vertraging":"","tussenstations":"Plainebourg", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR004-R1-' + '{:02}'.format(nummer) + 'H19M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"19", "bestemming":"Baie de Fleurs", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Plainebourg Midi, Champ Derrière, Fleurmont, Plateau de Fleurs", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""} \n')
            dienstregeling.write(', { "treincode":"GC-IC003-R2-' + '{:02}'.format(nummer) + 'H19M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"19", "bestemming":"Leusden", "vertrekspoor":"5","soort":"Intercité","vertraging":"","tussenstations":"Portail de l' + "'" + 'Ouest, Portailville, Souleause, Etendeau", "bericht":"Reistip: IC Sudport van ' + '{:02}'.format(nummer + 1) + ':21 is eerder in Leusden.", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}   \n')
            dienstregeling.write(', { "treincode":"GC-IC001-R2-' + '{:02}'.format(nummer) + 'H21M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"21", "bestemming":"Sudport", "vertrekspoor":"3","soort":"Intercité","vertraging":"","tussenstations":"Nouveau Paris Central, Leusden", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR004-R2-' + '{:02}'.format(nummer) + 'H22M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"22", "bestemming":"Nouveau Paris Sud", "vertrekspoor":"2","soort":"T.E. Regional","vertraging":"","tussenstations":"Gendte Quatier Avant, Formarais, Nouveau Paris C.", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR003-R2-' + '{:02}'.format(nummer) + 'H23M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"23", "bestemming":"Nouveau Paris Central", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Ville de Finpont, Canauxbourg, Canauxbourg Sud, Nouveau Paris Nord, Calais Midi", "bericht":"Reistip: TER Nouveau Paris Sud van ' + '{:02}'.format(nummer + 1) + ':23 is eerder in Nouveau Paris C.", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR003-R2-' + '{:02}'.format(nummer) + 'H28M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"28", "bestemming":"Gendte Ville Basse", "vertrekspoor":"2","soort":"T.E. Regional","vertraging":"","tussenstations":"", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}\n')
            dienstregeling.write(', { "treincode":"GC-IC001-R1-' + '{:02}'.format(nummer) + 'H33M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"33", "bestemming":"Baie de Fleurs", "vertrekspoor":"4","soort":"Intercité","vertraging":"","tussenstations":"", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR004-R1-' + '{:02}'.format(nummer) + 'H34M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"34", "bestemming":"Baie de Fleurs", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Plainebourg Midi, Champ Derrière, Fleurmont, Plateau de Fleurs", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-IC001-R2-' + '{:02}'.format(nummer) + 'H36M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"36", "bestemming":"Sudport", "vertrekspoor":"3","soort":"Intercité","vertraging":"","tussenstations":"Nouveau Paris Central, Leusden", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR004-R2-' + '{:02}'.format(nummer) + 'H37M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"37", "bestemming":"Etendeau", "vertrekspoor":"2","soort":"T.E. Regional","vertraging":"","tussenstations":"Gendte Quatier Avant, Formarais, Nouveau Paris C., Nouveau Paris Sud", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR003-R2-' + '{:02}'.format(nummer) + 'H38M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"38", "bestemming":"Nouveau Paris Central", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Ville de Finpont, Canauxbourg, Canauxbourg Sud, Nouveau Paris Nord, Calais Midi", "bericht":"Reistip: TER Etendeau van ' + '{:02}'.format(nummer + 1) + ':38 is eerder in Nouveau Paris C.", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR003-R2-' + '{:02}'.format(nummer) + 'H43M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"43", "bestemming":"Gendte Ville Basse", "vertrekspoor":"2","soort":"T.E. Regional","vertraging":"","tussenstations":"", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-IC001-R1-' + '{:02}'.format(nummer) + 'H48M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"48", "bestemming":"Baie de Fleurs", "vertrekspoor":"4","soort":"Intercité","vertraging":"","tussenstations":"Plainebourg", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR004-R1-' + '{:02}'.format(nummer) + 'H49M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"49", "bestemming":"Baie de Fleurs", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Plainebourg Midi, Champ Derrière, Fleurmont, Plateau de Fleurs", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-IC003-R2-' + '{:02}'.format(nummer) + 'H49M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"49", "bestemming":"Leusden", "vertrekspoor":"5","soort":"Intercité","vertraging":"","tussenstations":"Portail de l' + "'" + 'Ouest, Portailville, Souleause, Etendeau", "bericht":"Reistip: IC Sudport van ' + '{:02}'.format(nummer + 1) + ':51 is eerder in Leusden.", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}   \n')
            dienstregeling.write(', { "treincode":"GC-IC001-R2-' + '{:02}'.format(nummer) + 'H51M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"51", "bestemming":"Sudport", "vertrekspoor":"3","soort":"Intercité","vertraging":"","tussenstations":"Nouveau Paris Central, Leusden", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR004-R2-' + '{:02}'.format(nummer) + 'H52M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"52", "bestemming":"Nouveau Paris Sud", "vertrekspoor":"2","soort":"T.E. Regional","vertraging":"","tussenstations":"Gendte Quatier Avant, Formarais, Nouveau Paris C.", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR003-R2-' + '{:02}'.format(nummer) + 'H53M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"53", "bestemming":"Nouveau Paris Central", "vertrekspoor":"1","soort":"T.E. Regional","vertraging":"","tussenstations":"Plainebourg, Ville de Finpont, Canauxbourg, Canauxbourg Sud, Nouveau Paris Nord, Calais Midi", "bericht":"Reistip: TER Nouveau Paris Sud van ' + '{:02}'.format(nummer + 1) + ':53 is eerder in Nouveau Paris C.", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}  \n')
            dienstregeling.write(', { "treincode":"GC-TR003-R2-' + '{:02}'.format(nummer) + 'H58M", "vertrekuur":"' + '{:02}'.format(nummer) + '", "vertrekminuut":"58", "bestemming":"Gendte Ville Basse", "vertrekspoor":"2","soort":"T.E. Regional","vertraging":"","tussenstations":"", "bericht":"", "storingsoorzaak":"", "nieuweBestemming":"", "nieuwVertrekspoor":"","rijdtNiet":""}\n')
            if nummer == 24:
                dienstregeling.write(']}')
            print (nummer)
            nummer += 1
        dienstregeling.close()
else: print ('Niets gedaan')

print ('Ik ben klaar')


